import base64
import logging
from typing import Dict, Optional
from github import Github, GithubException
from github.GithubException import GithubException, UnknownObjectException
from config import settings

logger = logging.getLogger(__name__)

async def validate_github_token(token: str) -> bool:
    """Validate GitHub token"""
    try:
        g = Github(token)
        user = g.get_user()
        user.login  # This will raise exception if token is invalid
        return True
    except GithubException as e:
        logger.error(f"GitHub token validation failed: {str(e)}")
        return False

async def push_to_github(
    files: Dict[str, str],
    repo_name: str,
    token: str,
    description: str = "",
    private: bool = False
) -> str:
    """Push generated code files to GitHub repository"""
    try:
        g = Github(token)
        user = g.get_user()
        
        # Create repository
        try:
            repo = user.create_repo(
                name=repo_name,
                description=description or f"Generated by AI Code Manager Studio",
                private=private,
                auto_init=True
            )
            logger.info(f"Created repository: {repo_name}")
        except GithubException as e:
            if e.status == 422:  # Repository already exists
                try:
                    repo = user.get_repo(repo_name)
                    logger.info(f"Using existing repository: {repo_name}")
                except UnknownObjectException:
                    raise Exception(f"Cannot create or access repository: {repo_name}")
            else:
                raise

        # Get default branch
        default_branch = repo.default_branch
        logger.info(f"Using branch: {default_branch}")

        # Get current commit SHA
        try:
            contents = repo.get_contents("", ref=default_branch)
            current_commit_sha = repo.get_branch(default_branch).commit.sha
        except GithubException:
            current_commit_sha = None

        # Push each file
        for file_path, content in files.items():
            try:
                # Try to get existing file
                try:
                    existing_file = repo.get_contents(file_path, ref=default_branch)
                    # Update existing file
                    repo.update_file(
                        path=file_path,
                        message=f"Update {file_path} via AI Code Manager",
                        content=content,
                        sha=existing_file.sha,
                        branch=default_branch
                    )
                    logger.info(f"Updated file: {file_path}")
                except UnknownObjectException:
                    # Create new file
                    repo.create_file(
                        path=file_path,
                        message=f"Add {file_path} via AI Code Manager",
                        content=content,
                        branch=default_branch
                    )
                    logger.info(f"Created file: {file_path}")
                    
            except GithubException as e:
                logger.error(f"Error pushing {file_path}: {str(e)}")
                raise Exception(f"Failed to push {file_path}: {str(e)}")

        repo_url = repo.html_url
        logger.info(f"Successfully pushed to {repo_url}")
        
        return repo_url
        
    except GithubException as e:
        logger.error(f"GitHub API error: {str(e)}")
        if e.status == 401:
            raise Exception("Invalid GitHub token. Please check your token.")
        elif e.status == 422:
            raise Exception(f"Invalid repository name: {repo_name}")
        else:
            raise Exception(f"GitHub error: {str(e)}")
    except Exception as e:
        logger.error(f"Unexpected error in push_to_github: {str(e)}")
        raise

async def get_repository_info(token: str, repo_name: str) -> Optional[Dict]:
    """Get information about a repository"""
    try:
        g = Github(token)
        user = g.get_user()
        repo = user.get_repo(repo_name)
        
        return {
            "name": repo.name,
            "full_name": repo.full_name,
            "html_url": repo.html_url,
            "description": repo.description,
            "private": repo.private,
            "stars": repo.stargazers_count,
            "forks": repo.forks_count,
            "created_at": repo.created_at.isoformat() if repo.created_at else None,
            "updated_at": repo.updated_at.isoformat() if repo.updated_at else None,
        }
    except UnknownObjectException:
        return None
    except GithubException as e:
        logger.error(f"Error getting repo info: {str(e)}")
        return None