import os
from typing import Dict

from github import Github, GithubException


def push_to_github(files: Dict[str, str], repo_name: str, token: str) -> str:
    """
    Push files to a new GitHub repository.
    
    Args:
        files: Dictionary of filename -> content
        repo_name: Name of the repository to create
        token: GitHub personal access token
    
    Returns:
        URL of the created repository
    """
    if not token:
        raise ValueError("GitHub token is required")
    
    g = Github(token)
    user = g.get_user()
    
    # Check if repo already exists
    try:
        repo = user.get_repo(repo_name)
        # If exists, delete and recreate (or you could update)
        repo.delete()
    except GithubException:
        pass  # Repo doesn't exist, good
    
    # Create repository
    try:
        repo = user.create_repo(
            repo_name,
            description="Generated by AI Code Manager Studio",
            private=False,
            auto_init=False,
        )
    except GithubException as e:
        raise Exception(f"Failed to create repository: {e}")
    
    # Create initial commit with files
    try:
        # Create a .gitignore
        gitignore_content = """# Python
__pycache__/
*.py[cod]
*.so
.Python
env/
venv/
.env
*.egg-info/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""
        
        # Create files in the repository
        for filename, content in files.items():
            try:
                repo.create_file(
                    filename,
                    f"Add {filename}",
                    content,
                )
            except GithubException as e:
                # If file already exists, update it
                if e.status == 409:
                    contents = repo.get_contents(filename)
                    repo.update_file(
                        filename,
                        f"Update {filename}",
                        content,
                        contents.sha,
                    )
                else:
                    raise
        
        # Create .gitignore
        try:
            repo.create_file(
                ".gitignore",
                "Add .gitignore",
                gitignore_content,
            )
        except GithubException:
            pass  # Ignore if already exists
        
        # Create README.md
        readme_content = f"# {repo_name}\n\nGenerated by AI Code Manager Studio\n"
        try:
            repo.create_file(
                "README.md",
                "Add README.md",
                readme_content,
            )
        except GithubException:
            pass  # Ignore if already exists
        
    except GithubException as e:
        raise Exception(f"Failed to push files: {e}")
    
    return repo.html_url
